create table comment (id bigint generated by default as identity, body varchar(255), primary key (id));
create table article (id bigint generated by default as identity, body varchar(255), description varchar(255), favorited boolean not null, favorites_count integer not null, slug varchar(255), title varchar(255), user_id bigint, primary key (id));
create table follow_relation (followee_id bigint not null, follower_id bigint not null, primary key (followee_id, follower_id));
create table users (user_id bigint generated by default as identity, email varchar(255), password varchar(255), bio varchar(255), image varchar(255), username varchar(255), primary key (user_id));
create table tag (tag_id bigint generated by default as identity, tag varchar(255), primary key (tag_id));
